#!/bin/bash

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        # shellcheck source=/dev/null
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# enable window compositing
if [ -f /usr/bin/compton ]; then
    compton --config "$HOME/.compton.conf" --daemon
fi

numlockx &

# start i3 and keep it running
if [ -f /usr/bin/i3 ]; then
    cat ~/.i3/config.base ~/.i3/config.main > .i3/config
    $SUB=$(sleep 5 && xrdb ~/.Xresources)
    exec i3 
fi

