# $HOME/.zshrc
export EDITOR=vim
export KEYTIMEOUT=1

# load zgen
source "${HOME}/.zgen/zgen.zsh"

source ~/.secret

# if the init scipt doesn't exist
if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh

    # plugins
    zgen oh-my-zsh plugins/ssh-agent
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/python 
    zgen oh-my-zsh plugins/npm
    zgen oh-my-zsh plugins/docker
    zgen load edouard-lopez/yeoman-zsh-plugin
    zgen load tonyseek/oh-my-zsh-virtualenv-prompt
    zgen load ~/.zsh/themes/purvis

    #zgen load zsh-users/zsh-syntax-highlighting
    #zgen load zsh-users/zsh-completions src

    # save all to init script
    zgen save
fi


PATH=$PATH:$GOPATH/bin
PATH=$PATH:/home/josh/bin
PATH=$PATH:/usr/lib/w3m

bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word
HISTSIZE=9999
SAVEHIST=$HISTSIZE
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS 

# fix jvm/pycharm unicode bug which prevents keyboard input
export IBUS_ENABLE_SYNC_MODE=1

# share zsh history across shells
setopt inc_append_history
setopt share_history

# git log formatting
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

# add alias file if it exists
if [ -e ~/.zsh_alias ]; then
    source ~/.zsh_alias
fi

# Virtualenv Settings
export WORKON_HOME=$HOME/.env
export PROJECT_HOME=$HOME/src
source /usr/bin/virtualenvwrapper.sh

export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/home/josh/go/bin
export PATH=$PATH:/home/josh/.cargo/bin
export PATH=$PATH:/home/josh/.local/bin
export GOPATH=$HOME/projects

export PATH=$PATH:$HOME/bin

#[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

# ignore git in fzf
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'


# fix vim inside tmux
alias tmux="TERM=screen-256color-bce tmux"

# fixes for incremental search within tmux
#bindkey -e
#jbindkey '^R' history-incremental-search-backward
#bindkey '^[[A' up-line-or-search
#bindkey '^[[B' down-line-or-search

# enable control-s and control-q support
stty start undef
stty stop undef
setopt noflowcontrol


export TERM=rxvt-unicode-256color

# enable nvm
source /usr/share/nvm/init-nvm.sh

# prevent stupid single quotes everywhere with ls
export QUOTING_STYLE=literal

PATH="$PATH:$(ruby -e 'print Gem.user_dir')/bin"
export GEM_HOME=$HOME/.gem

source ~/bin/git-helpers

export GOCACHE=off
