---
- name: base | updated cache
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_ttl }}"
  tags:
    - base

- name: base | install basic packages
  become: yes
  apt:
    state: present
    name: "{{ item }}"
  with_items:
    - tree
    - curl
    - unzip
    - jq
    - xclip
    - graphviz
    - mercurial
    - apt-transport-https
    - software-properties-common
    - ca-certificates
    - apparmor
    - default-jdk
    - pandoc
    - tidy
    - tmux
    - nmap
    - openssh-server
    - openvpn
    - vim
    - htop
    - zsh
    - imagemagick
    - scrot
    #- virtualbox
    #- virtualbox-dkms
    #- virtualbox-guest-additions-iso
  tags:
    - packages
    - docker

- name: base | download vagrant
  become: yes
  shell: curl -o /tmp/vagrant.deb https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb
  tags: base

- name: base | install deb packages
  become: yes
  apt:
    deb: "{{ item }}"
  with_items:
    - "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    - "/tmp/vagrant.deb" 
  tags:
    - base

- name: base | install pip packages
  become: yes
  pip:
    name: "{{ item }}"
  with_items:
    - urllib3[secure]
    - virtualenv
    - virtualenvwrapper
  tags:
    - base
