
- name: docker | install python dependencies
  become: yes
  pip:
    name: "{{ item }}"
  with_items:
    - docker-compose
    - urllib3
    - pyopenssl
    - ndg-httpsclient
    - pyasn1
  tags:
    - docker

- name: docker | apt-key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  tags:
    - docker

- name: docker | add-apt-repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ debian_release }} stable"
    state: present
  tags:
    - docker

- name: docker | install
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_ttl }}"
  tags:
    - docker

- name: docker | add user to docker group
  become: yes
  user:
    name: "{{ default_user }}"
    groups: docker
    append: yes
  tags:
    - docker
