---
- name: go | check current version
  shell: go version | awk '{print $3}'
  register: golang_current_version
  changed_when: false
  tags:
    - golang

- name: go | download
  become: yes
  get_url:
    url: https://storage.googleapis.com/golang/{{ golang_version }}.linux-amd64.tar.gz
    dest: /tmp/
  register: golang_download
  when: golang_version != golang_current_version.stdout
  tags:
    - golang

- name: go | install
  become: yes
  unarchive:
    src: /tmp/{{ golang_version }}.linux-amd64.tar.gz
    dest: /usr/local
    copy: no
  when: golang_download.size is defined and golang_download.size > 0
  tags:
    - golang

- name: go | path
  become: no
  file:
    path: "{{ golang_path }}"
    state: directory
  tags:
    - golang

- name: go | dev dependencies
  become: no
  shell: "PATH=$PATH:/usr/local/go/bin GOPATH=\"{{ golang_path }}\" go get -u -v {{ item }}"
  with_items:
    - github.com/nsf/gocode
    - github.com/rogpeppe/godef
    - golang.org/x/tools/cmd/guru
    - golang.org/x/tools/cmd/gorename
    - golang.org/x/tools/cmd/goimports
    - github.com/nats-io/go-nats
    - github.com/Masterminds/glide
  tags:
    - golang