---
- name: nvm | stat
  stat:
    path: "{{ nvm_path }}"
  register: nvm_stat
  tags:
    - nvm

#- name: nvm | create ~/.nvm
#  file:
#    path: "{{ nvm_path }}"
#    group: "{{ nvm_user }}"
#    owner: "{{ nvm_user }}"
#    mode: 0755
#    recurse: yes
#    state: directory
#  when: not nvm_stat.stat.exists
#  tags:
#    - nvm

- name: nvm | download
  get_url:
    dest: "{{ nvm_path }}"
    url: https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/nvm.sh
  tags:
    - nvm
