---
- name: terraform | check version
  become: no
  shell: terraform version
  failed_when: false
  register: terraform_current_version
  tags:
    - terraform

- name: terraform | terraform is current?
  become: no
  set_fact:
    terraform_is_current: "{{ terraform_current_version.rc == 0 and terraform_current_version.stdout == ('Terraform v' + terraform_version) }}"
  tags:
    - terraform

- name: terraform | tmp directory
  become: no
  file:
    path: /tmp/terraform/
    state: directory
  when: not terraform_is_current
  tags:
    - terraform

- name: terraform | download
  become: no
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /tmp/terraform/terraform.zip
  when: not terraform_is_current
  tags:
    - terraform

- name: terraform | install
  become: yes
  unarchive:
    src: /tmp/terraform/terraform.zip
    dest: /usr/local/bin/
    copy: no
  when: not terraform_is_current
  tags:
    - terraform
